#!/usr/bin/env php
<?php

declare(strict_types=1);

$yiic = dirname(__FILE__) . '/src/vendor/yiisoft/yii/framework/yiic.php';
$config = dirname(__FILE__) . '/src/config/console.php';

require_once($yiic);
